### ISSUE TITLE
Cannot move windows to a secondary display.

### ISSUE THREAD

**Issue by iTerminate** [acristoffers/gnome-rectangle#1]
First, I wanted to say that this is an amazing extension! I've been using a different tiling manager on Linux but switching between mac and Linux was a headache due to different keyboard shortcuts and overall design. I've been looking for something like this for a while now.

Onto the issue, when using Rectangle for mac I can move a window to a different display using the combination (CTRL + Super + LEFT). With this extension I have to manually move the window to a different display after which the shortcuts work on the new display. 

Expected behavior is that pressing (CTRL + Super + LEFT) takes the window to the left of current display and pressing it again takes it to the new display on the right side. 

Let me know if there is a shortcut I'm missing,

**Comment by acristoffers** [comment]
Thanks. It's good to know it helps. The extension does not provide those because GNOME already have them. You can change their shortcuts in the Settings app, under `Keyboard`->`View and Customize Shortcuts` (last button, on the bottom) ->`Navigation`.

**Comment by iTerminate** [comment]
Thank your for the quick response! 
That seems to work okay. It seems that I need to run "super + left" before the move workspace shortcut works "super + shift + left". Maybe this is an issue my gnome version. If the window is placed by rectangle the shortcut doesn't work until I place it using the default tiling manager.

**Comment by acristoffers** [comment]
Hi again. Christmas gift for you: I just sent for revision a new version that adds 4 new shortcuts in the form of ⌘⌃⇧[Arrow] which moves the currently focused window to another adjacent monitor while keeping it in the grid. With them, if you use the right-two-thirds shortcut and sends it to another monitor, it will resize itself in the new monitor to also be in right-two-thirds size/position. I hope it serves your workflow better than the default shortcuts (which should work, and does work for me on Gnome 45, with the only problem that they do not resize the window, just move them, so they get whatever size they can get on the new monitor and may get off-screen on some situations).

**Comment by iTerminate** [comment]
Thank you! This helps with my workflow! I appreciate it! This is a great gnome extension! 

 Merry Christmas!
