### ISSUE TITLE
Configurable hotkeys

### ISSUE THREAD

**Issue by visvital** [acristoffers/gnome-rectangle#3]
### Story
As a user, I want to be able to modify the hard-coded hotkeys for the window placement rules, so that I could keep only the ones which are needed for my scenarios and disable the others.

### Acceptance criteria
1. The system introduces an option to modify the hotkeys for the available window placement rules.
2. When the user modifies the hotkeys for the selected rule, the system validates if the hotkey is used in any other place.
3. If the provided hotkey is used, the system provides the options to override the hotkey or to cancel the changes.
4. If the option to override the hotkey is applied, the system keeps the provided hotkey combination for the currently selected rule and removes this combination from the rule it was previously used.
5. The system introduces an option to remove the hotkeys for the window placement rules.
6. When the hotkey for the window placement rule is removed, the system considers the corresponding rule as disabled.

**Comment by acristoffers** [comment]
I'll try to get the option to modify the shortcuts in the settings now that I found an implementation that I like.

However, points 3 and 4 are not generally possible nor recommended by GNOME. GNOME does not provide a way to know what application is using what accelerator and is against one application/extension changing another application/extension's accelerators.

Points 5/6 will be covered by the option to modify the shortcuts already. I'll also consider adding a button to remove all accelerators at once, to facilitate mass-rebinding.

**Comment by acristoffers** [comment]
I've published the changes to the Gnome Extensions website for version 45. I don't know if/when I'll back-port it to 42-44 though, as that requires a lot of changes to the way the UI is currently built.
