### ISSUE TITLE
feature request: system tray icon to click to resize a window

### ISSUE THREAD

**Issue by joebb97** [acristoffers/gnome-rectangle#5]
This extension works great, I love rectangle on macOS. Thanks for making it.

One feature I'd love to have replicated is being able to click an icon in the system tray at the top of the screen to manually pick with the mouse what position to snap a window to.

**Comment by acristoffers** [comment]
Glad to know it serves you. However, you opened the issue at the end of Sunday, so I'll only be able to take a look at it next weekend, probably. What version of GNOME are you using? I'm kinda not willing to update older versions (duplicated work and all that), but for 45/46 I can take a give it a try.

**Comment by joebb97** [comment]
I am not an old version of GNOME, so 45/46 would be great.

And no rush at all, just an idea. Thanks for considering it!

**Comment by clintre** [comment]
I agree a context menu or a system tray menu would make this perfect. I love it, but remembering all the key combinations can be cumbersome. This has been my favorite system because you have kept it simple overall.

**Comment by acristoffers** [comment]
Just sent a version for review with a menu :)
