### ISSUE TITLE
Question: Implement the "smaller" and "larger" resize features of rectangle?

### ISSUE THREAD

**Issue by tommason14** [acristoffers/gnome-rectangle#7]
Hi,

This extension is perfect to replicate my macos workflow on gnome, thanks for creating it! I have one question, would it be possible to implement the "smaller" and "larger" bindings that are found in rectangle? So that all dimensions of a window shrink or increase by a set amount on a keypress?

**Comment by acristoffers** [comment]
I'm glad you like it ^^

I don't have a macOS anymore, can you describe better how those keybinding work? I don't remember
them.

- What are the shortcuts?
- How bigger/smaller? 10px? 100px? I may make it configurable, but I would like some sensible
default.
- Does the window grow from top-left or from the center? I'm guessing from center would be... nicer?

**Comment by tommason14** [comment]
Hi, the windows grow from the centre and that feels natural - I had a look on their website, looks like the default shortcuts are control+alt+= to grow and control+alt+- to shrink the window (but any binding would work as we can remap them).

By default, the windows increase or shrink by 30 pixels, https://github.com/rxhanson/Rectangle/blob/e1a37d16258304da5e9fddd4ece55634ed1731f3/TerminalCommands.md?plain=1#L323

**Comment by acristoffers** [comment]
I just uploaded a new version. There is an approval process, but you should see it update soon.

I named it shrink/expand and made the shortcuts "<super>-" and "<super>=" by default, to better align with the rest of the extension's shortcuts. I copied the 30px default.

Just a note: shortcut remapping isn't a given, I had to write a lot of code to have that working :P I wish it was more automated like in Plasma.

Thank you for your issue ^^

**Comment by tommason14** [comment]
Thanks for the quick response, this works perfectly
